title: DICES
description: Direct speech in Greek and Latin epic, from Homer to Nonnus
theme: minima
author:
  name: Chris Forstall
  email: cforstall@mta.ca
header_pages:
  - about.md
  - documentation.md